services:
  db:
    image: postgres:15.3
    container_name: psql-db
    environment:
      environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data across container restarts
